### ISSUE TITLE
⚡ Phase 2: GitHub Actions自動化統合

### ISSUE THREAD

**Issue by nyasuto** [nyasuto/beaver#10]
### **Priority: HIGH**

**Impact:** Workflow automation
**Component:** GitHub Actions Integration
**Files:** .github/workflows/, scripts/

### Problem Description

Beaverの知識生成プロセスをGitHub Actionsで自動化し、新しいIssueやコミットが発生した際に自動的にWikiを更新する仕組みを実装します。

### Recommended Solution

**GitHub Actions ワークフロー:**
- Issue作成/更新時の自動トリガー
- PR マージ時のWiki更新
- 定期実行による全体同期
- Slack/Teams への通知統合

**ワークフロー例:**
```yaml
name: Beaver Knowledge Update
on:
  issues:
    types: [opened, closed, labeled]
  pull_request:
    types: [closed]
  schedule:
    - cron: '0 2 * * *'  # 毎日2時に実行

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Beaver
        run: |
          beaver build --incremental
          beaver deploy wiki
```

### Technical Implementation

- `.github/workflows/beaver.yml` - メインワークフロー
- `scripts/ci-beaver.sh` - CI用スクリプト
- `pkg/actions/` - GitHub Actions統合
- 増分更新機能の実装

### Acceptance Criteria

- [ ] Issue イベントトリガーワークフロー作成
- [ ] PR マージ時の自動Wiki更新
- [ ] 定期実行による全体同期
- [ ] エラー時の通知システム
- [ ] 増分更新による処理効率化
- [ ] ワークフロー設定のドキュメント化
- [ ] CI/CDパイプラインとの統合テスト

**Phase 2 - 自動化による継続的知識更新**
