### ISSUE TITLE
📚 Phase 3: 外部ツール統合 (Notion/Confluence)

### ISSUE THREAD

**Issue by nyasuto** [nyasuto/beaver#13]
### **Priority: MEDIUM**

**Impact:** Multi-platform knowledge distribution
**Component:** External Platform Integration
**Files:** pkg/platforms/, integrations/

### Problem Description

GitHub Wiki以外の知識管理プラットフォーム (Notion、Confluence) への出力機能を実装します。チームが使用している既存の知識ベースに統合します。

### Recommended Solution

**外部プラットフォーム統合:**
- Notion API統合
- Confluence REST API統合
- プラットフォーム固有の形式変換
- 双方向同期機能

**対応プラットフォーム:**
- **Notion**: データベース、ページ作成
- **Confluence**: Space、Page管理
- **GitHub Wiki**: 既存機能拡張

**設定例:**
```yaml
output:
  platforms:
    - type: "notion"
      database_id: "xxx"
      token: "notion_token"
    - type: "confluence"
      space_key: "TEAM"
      url: "company.atlassian.net"
```

### Technical Implementation

- `pkg/platforms/notion.go` - Notion統合
- `pkg/platforms/confluence.go` - Confluence統合
- `pkg/formats/` - 形式変換エンジン
- プラットフォーム別テンプレート

### Acceptance Criteria

- [ ] Notion API統合とページ作成
- [ ] Confluence Space/Page管理
- [ ] プラットフォーム別形式変換
- [ ] 設定ファイルでの出力先管理
- [ ] 双方向同期機能 (読み取り)
- [ ] エラーハンドリングとリトライ
- [ ] CLI コマンド `beaver deploy <platform>` 実装

**Phase 3 - 既存知識ベースへの統合**
