### ISSUE TITLE
⚙️ Phase 1: CLIコマンド統合 (init, build, status)

### ISSUE THREAD

**Issue by nyasuto** [nyasuto/beaver#6]
### **Priority: HIGH**

**Impact:** User interface and workflow
**Component:** CLI Application
**Files:** cmd/beaver/, internal/cli/

### Problem Description

Phase 1の各機能を統合し、READMEで定義されたCLIコマンド (`beaver init`, `beaver build`, `beaver status`) を実装します。ユーザーフレンドリーなコマンドラインインターフェースを提供します。

### Recommended Solution

**CLI コマンド実装:**

1. **beaver init** - プロジェクト初期化
   - 設定ファイル (beaver.yml) 生成
   - GitHub token設定
   - AI API設定

2. **beaver build** - Issues → Wiki変換実行
   - GitHub Issues取得
   - AI処理実行
   - Wiki生成・投稿

3. **beaver status** - 処理状況表示
   - 最新処理状況
   - エラーログ表示
   - 統計情報

**設定ファイル例:**
```yaml
project:
  name: "My AI Learning Record"
  repository: "username/my-repo"
sources:
  github:
    issues: true
ai:
  provider: "openai"
  model: "gpt-4"
```

### Technical Implementation

- `cmd/beaver/main.go` - CLIエントリーポイント
- `internal/cli/` - サブコマンド実装
- `internal/config/` - 設定管理
- cobra CLI frameworkを使用

### Acceptance Criteria

- [ ] `beaver init` コマンド実装と設定ファイル生成
- [ ] `beaver build` コマンドで全工程実行
- [ ] `beaver status` で処理状況表示
- [ ] 設定ファイル (beaver.yml) 管理機能
- [ ] エラーハンドリングとユーザーフレンドリーなメッセージ
- [ ] ヘルプとUsage表示
- [ ] 実際のワークフロー動作確認

**Phase 1 MVP完成 - エンドツーエンドワークフロー**
